server:
  port: 8070

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://192.168.2.151:8761/eureka/

spring:
  application:
    name: eureka-consumer-feign-hystrix