server:
  port: 8086

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wesleywong/demo-config-repo.git
          username:
          password: