server:
  port: 8080

logging:
  level:
    root: INFO

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://10.100.152.53:8761/eureka/

spring:
  application:
    name: wesley-common