server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
  #  禁用eureka注册自己作为客户端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0